version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_cont
    ports: 
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-network


  django_app:
    build:
      context: .
    image: my-app
    container_name: django_cont
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: always
    depends_on: 
      - db
    networks:
      - notes-app-network
  



  db:
    image: mysql
    container_name: db_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - notes-app:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-network

networks:
  notes-app-network:
volumes:
  notes-app:
